# Generated by Django 2.2 on 2019-07-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBFApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('blood_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('HCV', models.BooleanField()),
                ('HIV', models.BooleanField()),
                ('HBsAg', models.BooleanField()),
                ('Syphilis', models.BooleanField()),
                ('MP', models.BooleanField()),
            ],
            options={
                'db_table': 'blood_test',
            },
        ),
    ]
