# Generated by Django 2.2 on 2019-07-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBFApp', '0002_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('bag_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=5)),
                ('rh_type', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stored_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('available', models.CharField(default='available', editable='true', max_length=20)),
                ('blood_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BBFApp.BloodTest')),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
