# Generated by Django 2.2 on 2019-07-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBFApp', '0003_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('serial_no', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=5)),
                ('blood_group', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('referred_by', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('cabin_bed', models.CharField(max_length=20)),
                ('issue_voucher_no', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
                ('bag_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='BBFApp.Storage')),
            ],
            options={
                'db_table': 'Recipient',
            },
        ),
    ]
