# Generated by Django 2.2 on 2019-07-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBFApp', '0006_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BBFApp.Donor')),
                ('permitted_to_donate', models.BooleanField()),
                ('donor_consent', models.CharField(max_length=20)),
                ('doctor_consent', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Consent',
            },
        ),
    ]
