# Generated by Django 2.2 on 2019-07-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBFApp', '0009_physicaltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationHistory',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BBFApp.Donor')),
                ('blood_donate_before_boolean', models.BooleanField()),
                ('gap_of_blood_donation', models.CharField(max_length=20)),
                ('is_recipient_relative', models.BooleanField()),
                ('patient_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blood_Donation_History',
            },
        ),
    ]
