# Generated by Django 2.2 on 2019-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBFApp', '0011_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='donor',
            name='father_or_husband_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='mobile_number',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='occupation',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
